import Head from 'next/head'
import Image from 'next/image'

import React, { useState } from 'react';
import LoginPage from '../components/LoginPage';

export default function Home() {
  const [login, setLogin] = useState(false);

  return (
    < >
      <Head>
        <title>Alpha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
      {/* */}
    
    </>
  )
}
